# Generated by Django 5.2.6 on 2025-09-14 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='MovieID')),
                ('movie_title', models.CharField(max_length=200, verbose_name='MovieTitle')),
                ('actor1_name', models.CharField(max_length=120, verbose_name='Actor1Name')),
                ('actor2_name', models.CharField(blank=True, max_length=120, verbose_name='Actor2Name')),
                ('director_name', models.CharField(max_length=120, verbose_name='DirectorName')),
                ('movie_genre', models.CharField(choices=[('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Action', 'Action'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi')], max_length=20, verbose_name='MovieGenre')),
                ('release_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2026)], verbose_name='ReleaseYear')),
            ],
        ),
    ]
